<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>
  <ItemGroup>

<ProjectReference Include="..\GSMApplication.Entities\GSMApplication.Entities.csproj" />
<ProjectReference Include="..\GSMApplication.Abstractions\GSMApplication.Abstractions.csproj" />


  </ItemGroup>
</Project>
