<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>
  <ItemGroup>

<ProjectReference Include="..\GSMAuth.Abstractions\GSMAuth.Abstractions.csproj" />
<ProjectReference Include="..\GSMAuth.Entities\GSMAuth.Entities.csproj" />
<ProjectReference Include="..\GSMAuth.Tenant\GSMAuth.Tenant.csproj" />
<ProjectReference Include="..\GSMAuth.DataAccess\GSMAuth.DataAccess.csproj" />
<ProjectReference Include="..\GSMAuth.Infrastructure\GSMAuth.Infrastructure.csproj" />


  </ItemGroup>
</Project>
